/* Auto-generated card image dictionary */
const cardImages = {
  "Abundance": "images/plunder/plunder_abundance.jpg",
  "Academy": "images/renaissance/renaissance_project_academy.jpg",
  "Acting Troupe": "images/renaissance/renaissance_actingtroupe.jpg",
  "Advance": "images/empires/empires_event_advance.jpg",
  "Advisor": "images/guilds/guilds_advisor.jpg",
  "Alchemist": "images/alchemy/alchemy_alchemist.jpg",
  "Alley": "images/risingsun/risingsun_alley.jpg",
  "Alliance": "images/menagerie/menagerie_event_alliance.jpg",
  "Alms": "images/adventures/adventures_event_alms.jpg",
  "Altar": "images/darkages/darkages_altar.jpg",
  "Amass": "images/risingsun/risingsun_event_amass.jpg",
  "Amulet": "images/adventures/adventures_amulet.jpg",
  "Animal Fair": "images/menagerie/menagerie_animalfair.jpg",
  "Annex": "images/empires/empires_event_annex.jpg",
  "Anvil": "images/prosperity2add/prosperity2add_anvil.jpg",
  "Apothecary": "images/alchemy/alchemy_apothecary.jpg",
  "Apprentice": "images/alchemy/alchemy_apprentice.jpg",
  "Approaching Army": "images/risingsun/risingsun_prophecy_approachingarmy.jpg",
  "Aqueduct": "images/empires/empires_landmark_aqueduct.jpg",
  "Architects' Guild": "images/allies/allies_ally_architectsguild.jpg",
  "Archive": "images/empires/empires_archive.jpg",
  "Arena": "images/empires/empires_landmark_arena.jpg",
  "Aristocrat": "images/risingsun/risingsun_aristocrat.jpg",
  "Armory": "images/darkages/darkages_armory.jpg",
  "Artificer": "images/adventures/adventures_artificer.jpg",
  "Artisan": "images/baseset2add/baseset2add_artisan.jpg",
  "Artist": "images/risingsun/risingsun_artist.jpg",
  "Asceticism": "images/risingsun/risingsun_event_asceticism.jpg",
  "Astrolabe": "images/seaside2add/seaside2add_astrolabe.jpg",
  "Augurs": "images/allies/allies_augurs.jpg",
  "Avoid": "images/plunder/plunder_event_avoid.jpg",
  "Baker": "images/guilds/guilds_baker.jpg",
  "Ball": "images/adventures/adventures_event_ball.jpg",
  "Band of Misfits": "images/darkages/darkages_bandofmisfits.jpg",
  "Band of Nomads": "images/allies/allies_ally_bandofnomads.jpg",
  "Bandit": "images/baseset2add/baseset2add_bandit.jpg",
  "Bandit Camp": "images/darkages/darkages_banditcamp.jpg",
  "Bandit Fort": "images/empires/empires_landmark_banditfort.jpg",
  "Banish": "images/menagerie/menagerie_event_banish.jpg",
  "Bank": "images/prosperity/prosperity_bank.jpg",
  "Banquet": "images/empires/empires_event_banquet.jpg",
  "Barbarian": "images/allies/allies_barbarian.jpg",
  "Bard": "images/nocturne/nocturne_bard.jpg",
  "Bargain": "images/menagerie/menagerie_event_bargain.jpg",
  "Barge": "images/menagerie/menagerie_barge.jpg",
  "Baron": "images/intrigue2/intrigue2_baron.jpg",
  "Barracks": "images/renaissance/renaissance_project_barracks.jpg",
  "Basilica": "images/empires/empires_landmark_basilica.jpg",
  "Bat": "images/nocturne/nocturne_bat.jpg",
  "Baths": "images/empires/empires_landmark_baths.jpg",
  "Battlefield": "images/empires/empires_landmark_battlefield.jpg",
  "Bauble": "images/allies/allies_bauble.jpg",
  "Bazaar": "images/seaside/seaside_bazaar.jpg",
  "Beggar": "images/darkages/darkages_beggar.jpg",
  "Berserker": "images/hinterlands2add/hinterlands2add_berserker.jpg",
  "Biding Time": "images/risingsun/risingsun_prophecy_bidingtime.jpg",
  "Bishop": "images/prosperity/prosperity_bishop.jpg",
  "Black Cat": "images/menagerie/menagerie_blackcat.jpg",
  "Blessed Village": "images/nocturne/nocturne_blessedvillage.jpg",
  "Blockade": "images/seaside2add/seaside2add_blockade.jpg",
  "Bonfire": "images/adventures/adventures_event_bonfire.jpg",
  "Boons": "images/nocturne/nocturne_boon_theearthsgift.jpg",
  "Border Guard": "images/renaissance/renaissance_borderguard.jpg",
  "Border Village": "images/hinterlands/hinterlands_bordervillage.jpg",
  "Borrow": "images/adventures/adventures_event_borrow.jpg",
  "Bounty Hunter": "images/menagerie/menagerie_bountyhunter.jpg",
  "Bridge": "images/intrigue2/intrigue2_bridge.jpg",
  "Bridge Troll": "images/adventures/adventures_bridgetroll.jpg",
  "Broker": "images/allies/allies_broker.jpg",
  "Bureaucracy": "images/risingsun/risingsun_prophecy_bureaucracy.jpg",
  "Bureaucrat": "images/baseset2/baseset2_bureaucrat.jpg",
  "Buried Treasure": "images/plunder/plunder_buriedtreasure.jpg",
  "Bury": "images/plunder/plunder_event_bury.jpg",
  "Butcher": "images/guilds/guilds_butcher.jpg",
  "Cabin Boy": "images/plunder/plunder_cabinboy.jpg",
  "Cage": "images/plunder/plunder_cage.jpg",
  "Camel Train": "images/menagerie/menagerie_cameltrain.jpg",
  "Canal": "images/renaissance/renaissance_project_canal.jpg",
  "Candlestick Maker": "images/guilds/guilds_candlestickmaker.jpg",
  "Capital": "images/empires/empires_capital.jpg",
  "Capital City": "images/allies/allies_capitalcity.jpg",
  "Capitalism": "images/renaissance/renaissance_project_capitalism.jpg",
  "Caravan": "images/seaside/seaside_caravan.jpg",
  "Caravan Guard": "images/adventures/adventures_caravanguard.jpg",
  "Cardinal": "images/menagerie/menagerie_cardinal.jpg",
  "Cargo Ship": "images/renaissance/renaissance_cargoship.jpg",
  "Carnival": "images/guildscornucopia2add/guildscornucopia2add_carnival.jpg",
  "Carpenter": "images/allies/allies_carpenter.jpg",
  "Cartographer": "images/hinterlands/hinterlands_cartographer.jpg",
  "Castles": "images/empires/empires_castles.jpg",
  "Catacombs": "images/darkages/darkages_catacombs.jpg",
  "Catapult / Rocks": "images/empires/empires_catapultrocks.jpg",
  "Cathedral": "images/renaissance/renaissance_project_cathedral.jpg",
  "Cauldron": "images/hinterlands2add/hinterlands2add_cauldron.jpg",
  "Cavalry": "images/menagerie/menagerie_cavalry.jpg",
  "Cave Dwellers": "images/allies/allies_ally_cavedwellers.jpg",
  "Cellar": "images/baseset2/baseset2_cellar.jpg",
  "Cemetary": "images/nocturne/nocturne_cemetery.jpg",
  "Cemetery": "images/nocturne/nocturne_cemetery.jpg",
  "Champion": "images/adventures/adventures_champion.jpg",
  "Change": "images/risingsun/risingsun_change.jpg",
  "Changeling": "images/nocturne/nocturne_changeling.jpg",
  "Chapel": "images/baseset2/baseset2_chapel.jpg",
  "Chariot Race": "images/empires/empires_chariotrace.jpg",
  "Charlatan": "images/prosperity2add/prosperity2add_charlatan.jpg",
  "Charm": "images/empires/empires_charm.jpg",
  "Cheap": "images/plunder/plunder_trait_cheap.jpg",
  "Circle of Witches": "images/allies/allies_ally_circleofwitches.jpg",
  "Citadel": "images/renaissance/renaissance_project_citadel.jpg",
  "City": "images/prosperity/prosperity_city.jpg",
  "City Gate": "images/renaissance/renaissance_project_citygate.jpg",
  "City Quarter": "images/empires/empires_cityquarter.jpg",
  "City-State": "images/allies/allies_ally_citystate.jpg",
  "Clashes": "images/allies/allies_clashes.jpg",
  "Clerk": "images/prosperity2add/prosperity2add_clerk.jpg",
  "Coastal Haven": "images/allies/allies_ally_coastalhaven.jpg",
  "Cobbler": "images/nocturne/nocturne_cobbler.jpg",
  "Coin of the Realm": "images/adventures/adventures_coinoftherealm.jpg",
  "Collection": "images/prosperity2add/prosperity2add_collection.jpg",
  "Colonnade": "images/empires/empires_landmark_colonnade.jpg",
  "Colony": "images/prosperity/prosperity_colony.jpg",
  "Commerce": "images/menagerie/menagerie_event_commerce.jpg",
  "Conclave": "images/nocturne/nocturne_conclave.jpg",
  "Conquest": "images/empires/empires_event_conquest.jpg",
  "Conspirator": "images/intrigue2/intrigue2_conspirator.jpg",
  "Continue": "images/risingsun/risingsun_event_continue.jpg",
  "Contract": "images/allies/allies_contract.jpg",
  "Copper": "images/baseset2/baseset2_copper.jpg",
  "Corsair": "images/seaside2add/seaside2add_corsair.jpg",
  "Council Room": "images/baseset2/baseset2_councilroom.jpg",
  "Count": "images/darkages/darkages_count.jpg",
  "Counterfeit": "images/darkages/darkages_counterfeit.jpg",
  "Courier": "images/allies/allies_courier.jpg",
  "Courtier": "images/intrigue2add/intrigue2add_courtier.jpg",
  "Courtyard": "images/intrigue2/intrigue2_courtyard.jpg",
  "Coven": "images/menagerie/menagerie_coven.jpg",
  "Crafter's Guild": "images/allies/allies_ally_craftersguild.jpg",
  "Craftsman": "images/risingsun/risingsun_craftsman.jpg",
  "Credit": "images/risingsun/risingsun_event_credit.jpg",
  "Crew": "images/plunder/plunder_crew.jpg",
  "Crop Rotation": "images/renaissance/renaissance_project_croprotation.jpg",
  "Crossroads": "images/hinterlands/hinterlands_crossroads.jpg",
  "Crown": "images/empires/empires_crown.jpg",
  "Crucible": "images/plunder/plunder_crucible.jpg",
  "Crypt": "images/nocturne/nocturne_crypt.jpg",
  "Crystal Ball": "images/prosperity2add/prosperity2add_crystalball.jpg",
  "Cultist": "images/darkages/darkages_cultist.jpg",
  "Curse": "images/baseset2/baseset2_curse.jpg",
  "Cursed": "images/plunder/plunder_trait_cursed.jpg",
  "Cursed Gold": "images/nocturne/nocturne_cursedgold.jpg",
  "Cursed Village": "images/nocturne/nocturne_cursedvillage.jpg",
  "Cutpurse": "images/seaside/seaside_cutpurse.jpg",
  "Cutthroat": "images/plunder/plunder_cutthroat.jpg",
  "Daimyo": "images/risingsun/risingsun_daimyo.jpg",
  "Death Cart": "images/darkages/darkages_deathcart.jpg",
  "Defiled Shrine": "images/empires/empires_landmark_defiledshrine.jpg",
  "Delay": "images/menagerie/menagerie_event_delay.jpg",
  "Deliver": "images/plunder/plunder_event_deliver.jpg",
  "Delve": "images/empires/empires_event_delve.jpg",
  "Demand": "images/menagerie/menagerie_event_demand.jpg",
  "Den of Sin": "images/nocturne/nocturne_denofsin.jpg",
  "Desert Guides": "images/allies/allies_ally_desertguides.jpg",
  "Desperation": "images/menagerie/menagerie_event_desperation.jpg",
  "Destrier": "images/menagerie/menagerie_destrier.jpg",
  "Develop": "images/hinterlands/hinterlands_develop.jpg",
  "Devil's Workshop": "images/nocturne/nocturne_devilsworkshop.jpg",
  "Diplomat": "images/intrigue2add/intrigue2add_diplomat.jpg",
  "Disciple": "images/adventures/adventures_disciple.jpg",
  "Displace": "images/menagerie/menagerie_displace.jpg",
  "Distant Lands": "images/adventures/adventures_distantlands.jpg",
  "Divine Wind": "images/risingsun/risingsun_prophecy_divinewind.jpg",
  "Divine Wind, Receive Tribute": "images/risingsun/risingsun_prophecy_divinewind.jpg",
  "Doctor": "images/guilds/guilds_doctor.jpg",
  "Dominate": "images/empires/empires_event_dominate.jpg",
  "Donate": "images/empires/empires_event_donate.jpg",
  "Druid": "images/nocturne/nocturne_druid.jpg",
  "Ducat": "images/renaissance/renaissance_ducat.jpg",
  "Duchy": "images/baseset2/baseset2_duchy.jpg",
  "Duke": "images/intrigue2/intrigue2_duke.jpg",
  "Dungeon": "images/adventures/adventures_dungeon.jpg",
  "Duplicate": "images/adventures/adventures_duplicate.jpg",
  "Emissary": "images/allies/allies_emissary.jpg",
  "Encampment / Plunder": "images/empires/empires_encampmentplunder.jpg",
  "Enchantress": "images/empires/empires_enchantress.jpg",
  "Enclave": "images/menagerie/menagerie_event_enclave.jpg",
  "Engineer": "images/empires/empires_engineer.jpg",
  "Enhance": "images/menagerie/menagerie_event_enhance.jpg",
  "Enlarge": "images/plunder/plunder_enlarge.jpg",
  "Enlightenment": "images/risingsun/risingsun_prophecy_enlightenment.jpg",
  "Estate": "images/baseset2/baseset2_estate.jpg",
  "Exorcist": "images/nocturne/nocturne_exorcist.jpg",
  "Expand": "images/prosperity/prosperity_expand.jpg",
  "Expedition": "images/adventures/adventures_event_expedition.jpg",
  "Experiment": "images/renaissance/renaissance_experiment.jpg",
  "Exploration": "images/renaissance/renaissance_project_exploration.jpg",
  "Fair": "images/renaissance/renaissance_project_fair.jpg",
  "Fairgrounds": "images/cornucopia/cornucopia_fairgrounds.jpg",
  "Faithful Hound": "images/nocturne/nocturne_faithfulhound.jpg",
  "Falconer": "images/menagerie/menagerie_falconer.jpg",
  "Familiar": "images/alchemy/alchemy_familiar.jpg",
  "Family of Inventors": "images/allies/allies_ally_familyofinventors.jpg",
  "Farm": "images/guildscornucopia2add/guildscornucopia2add_farmhands.jpg",
  "Farmers' Market": "images/empires/empires_farmersmarket.jpg",
  "Farmhands": "images/guildscornucopia2add/guildscornucopia2add_farmhands.jpg",
  "Farming Village": "images/cornucopia/cornucopia_farmingvillage.jpg",
  "Farmland": "images/hinterlands/hinterlands_farmland.jpg",
  "Farrier": "images/guildscornucopia2add/guildscornucopia2add_farrier.jpg",
  "Fated": "images/plunder/plunder_trait_fated.jpg",
  "Fawning": "images/plunder/plunder_trait_fawning.jpg",
  "Fellowship of Scribes": "images/allies/allies_ally_fellowshipofscribes.jpg",
  "Feodum": "images/darkages/darkages_feodum.jpg",
  "Ferry": "images/adventures/adventures_event_ferry.jpg",
  "Ferryman": "images/guildscornucopia2add/guildscornucopia2add_ferryman.jpg",
  "Festival": "images/baseset2/baseset2_festival.jpg",
  "Figurine": "images/plunder/plunder_figurine.jpg",
  "First Mate": "images/plunder/plunder_firstmate.jpg",
  "Fisherman": "images/menagerie/menagerie_fisherman.jpg",
  "Fishing Village": "images/seaside/seaside_fishingvillage.jpg",
  "Fishmonger": "images/risingsun/risingsun_fishmonger.jpg",
  "Flag": "images/renaissance/renaissance_flag.jpg",
  "Flag Bearer": "images/renaissance/renaissance_flagbearer.jpg",
  "Flagship": "images/plunder/plunder_flagship.jpg",
  "Fleet": "images/renaissance/renaissance_project_fleet.jpg",
  "Flourishing Trade": "images/risingsun/risingsun_prophecy_flourishingtrade.jpg",
  "Fool": "images/nocturne/nocturne_fool.jpg",
  "Fool's Gold": "images/hinterlands/hinterlands_foolsgold.jpg",
  "Footpad": "images/guildscornucopia2add/guildscornucopia2add_footpad.jpg",
  "Forager": "images/darkages/darkages_forager.jpg",
  "Foray": "images/plunder/plunder_event_foray.jpg",
  "Foresight": "images/risingsun/risingsun_event_foresight.jpg",
  "Forest Dwellers": "images/allies/allies_ally_forestdwellers.jpg",
  "Forge": "images/prosperity/prosperity_forge.jpg",
  "Fortress": "images/darkages/darkages_fortress.jpg",
  "Forts": "images/allies/allies_forts.jpg",
  "Fortune Hunter": "images/plunder/plunder_fortunehunter.jpg",
  "Fortune Teller": "images/cornucopia/cornucopia_fortuneteller.jpg",
  "Forum": "images/empires/empires_forum.jpg",
  "Fountain": "images/empires/empires_landmark_fountain.jpg",
  "Friendly": "images/plunder/plunder_trait_friendly.jpg",
  "Frigate": "images/plunder/plunder_frigate.jpg",
  "Fugitive": "images/adventures/adventures_fugitive.jpg",
  "Galleria": "images/allies/allies_galleria.jpg",
  "Gamble": "images/menagerie/menagerie_event_gamble.jpg",
  "Gang of Pickpockets": "images/allies/allies_ally_gangofpickpockets.jpg",
  "Gardens": "images/baseset2/baseset2_gardens.jpg",
  "Gatekeeper": "images/menagerie/menagerie_gatekeeper.jpg",
  "Gather": "images/risingsun/risingsun_event_gather.jpg",
  "Gear": "images/adventures/adventures_gear.jpg",
  "Ghost": "images/nocturne/nocturne_ghost.jpg",
  "Ghost Town": "images/nocturne/nocturne_ghosttown.jpg",
  "Giant": "images/adventures/adventures_giant.jpg",
  "Gladiator / Fortune": "images/empires/empires_gladiatorfortune.jpg",
  "Goat": "images/nocturne/nocturne_goat.jpg",
  "Goatherd": "images/menagerie/menagerie_goatherd.jpg",
  "Gold": "images/baseset2/baseset2_gold.jpg",
  "Gold Mine": "images/risingsun/risingsun_goldmine.jpg",
  "Golem": "images/alchemy/alchemy_golem.jpg",
  "Gondola": "images/plunder/plunder_gondola.jpg",
  "Good Harvest": "images/risingsun/risingsun_prophecy_goodharvest.jpg",
  "Grand Market": "images/prosperity/prosperity_grandmarket.jpg",
  "Graverobber": "images/darkages/darkages_graverobber.jpg",
  "Great Leader": "images/risingsun/risingsun_prophecy_greatleader.jpg",
  "Groom": "images/menagerie/menagerie_groom.jpg",
  "Grotto": "images/plunder/plunder_grotto.jpg",
  "Groundskeeper": "images/empires/empires_groundskeeper.jpg",
  "Growth": "images/risingsun/risingsun_prophecy_growth.jpg",
  "Guard Dog": "images/hinterlands2add/hinterlands2add_guarddog.jpg",
  "Guardian": "images/nocturne/nocturne_guardian.jpg",
  "Guide": "images/adventures/adventures_guide.jpg",
  "Guildhall": "images/renaissance/renaissance_project_guildhall.jpg",
  "Guildmaster": "images/allies/allies_guildmaster.jpg",
  "Haggler": "images/hinterlands/hinterlands_haggler.jpg",
  "Hamlet": "images/cornucopia/cornucopia_hamlet.jpg",
  "Harbinger": "images/baseset2add/baseset2add_harbinger.jpg",
  "Harbor Village": "images/plunder/plunder_harborvillage.jpg",
  "Harem": "images/intrigue2/intrigue2_harem.jpg",
  "Harsh Winter": "images/risingsun/risingsun_prophecy_harshwinter.jpg",
  "Harsh Winter, Amass": "images/risingsun/risingsun_prophecy_harshwinter.jpg",
  "Harvest": "images/cornucopia/cornucopia_harvest.jpg",
  "Hasty": "images/plunder/plunder_trait_hasty.jpg",
  "Haunted Mirror": "images/nocturne/nocturne_hauntedmirror.jpg",
  "Haunted Woods": "images/adventures/adventures_hauntedwoods.jpg",
  "Haven": "images/seaside/seaside_haven.jpg",
  "Herald": "images/guilds/guilds_herald.jpg",
  "Herbalist": "images/alchemy/alchemy_herbalist.jpg",
  "Hermit": "images/darkages/darkages_hermit.jpg",
  "Hero": "images/adventures/adventures_hero.jpg",
  "Hexes": "images/nocturne/nocturne_badomens.jpg",
  "Hideout": "images/renaissance/renaissance_hideout.jpg",
  "Highway": "images/hinterlands/hinterlands_highway.jpg",
  "Highwayman": "images/allies/allies_highwayman.jpg",
  "Hireling": "images/adventures/adventures_hireling.jpg",
  "Hoard": "images/prosperity/prosperity_hoard.jpg",
  "Horn": "images/renaissance/renaissance_horn.jpg",
  "Horn of Plenty": "images/cornucopia/cornucopia_hornofplenty.jpg",
  "Horse": "images/menagerie/menagerie_horse.jpg",
  "Horse Traders": "images/cornucopia/cornucopia_horsetraders.jpg",
  "Hostelry": "images/menagerie/menagerie_hostelry.jpg",
  "Hovel": "images/darkages/darkages_hovel.jpg",
  "Hunter": "images/allies/allies_hunter.jpg",
  "Hunting Grounds": "images/darkages/darkages_huntinggrounds.jpg",
  "Hunting Lodge": "images/menagerie/menagerie_huntinglodge.jpg",
  "Hunting Party": "images/cornucopia/cornucopia_huntingparty.jpg",
  "Idol": "images/nocturne/nocturne_idol.jpg",
  "Imp": "images/nocturne/nocturne_imp.jpg",
  "Imperial Envoy": "images/risingsun/risingsun_imperialenvoy.jpg",
  "Importer": "images/allies/allies_importer.jpg",
  "Improve": "images/renaissance/renaissance_improve.jpg",
  "Infirmary": "images/guildscornucopia2add/guildscornucopia2add_infirmary.jpg",
  "Inheritance": "images/adventures/adventures_event_inheritance.jpg",
  "Inherited": "images/plunder/plunder_trait_inherited.jpg",
  "Inn": "images/hinterlands/hinterlands_inn.jpg",
  "Innkeeper": "images/allies/allies_innkeeper.jpg",
  "Innovation": "images/renaissance/renaissance_project_innovation.jpg",
  "Inspiring": "images/plunder/plunder_trait_inspiring.jpg",
  "Invasion": "images/plunder/plunder_event_invasion.jpg",
  "Inventor": "images/renaissance/renaissance_inventor.jpg",
  "Invest": "images/menagerie/menagerie_event_invest.jpg",
  "Investment": "images/prosperity2add/prosperity2add_investment.jpg",
  "Ironmonger": "images/darkages/darkages_ironmonger.jpg",
  "Ironworks": "images/intrigue2/intrigue2_ironworks.jpg",
  "Island": "images/seaside/seaside_island.jpg",
  "Island Folk": "images/allies/allies_ally_islandfolk.jpg",
  "Jack of all Trades": "images/hinterlands/hinterlands_jackofalltrades.jpg",
  "Jester": "images/cornucopia/cornucopia_jester.jpg",
  "Jewelled Egg": "images/plunder/plunder_jewelledegg.jpg",
  "Journey": "images/plunder/plunder_event_journey.jpg",
  "Journeyman": "images/guilds/guilds_journeyman.jpg",
  "Joust": "images/guildscornucopia2add/guildscornucopia2add_joust.jpg",
  "Junk Dealer": "images/darkages/darkages_junkdealer.jpg",
  "Keep": "images/empires/empires_landmark_keep.jpg",
  "Key": "images/renaissance/renaissance_key.jpg",
  "Kiln": "images/menagerie/menagerie_kiln.jpg",
  "Kind Emperor": "images/risingsun/risingsun_prophecy_kindemperor.jpg",
  "King's Cache": "images/plunder/plunder_kingscache.jpg",
  "King's Court": "images/prosperity/prosperity_kingscourt.jpg",
  "Kintsugi": "images/risingsun/risingsun_event_kintsugi.jpg",
  "Kitsune": "images/risingsun/risingsun_kitsune.jpg",
  "Knights": "images/darkages/darkages_knights.jpg",
  "Laboratory": "images/baseset2/baseset2_laboratory.jpg",
  "Labyrinth": "images/empires/empires_landmark_labyrinth.jpg",
  "Lackeys": "images/renaissance/renaissance_lackeys.jpg",
  "Landing Party": "images/plunder/plunder_landingparty.jpg",
  "Lantern": "images/renaissance/renaissance_lantern.jpg",
  "Launch": "images/plunder/plunder_event_launch.jpg",
  "League of Bankers": "images/allies/allies_ally_leagueofbankers.jpg",
  "League of Shopkeepers": "images/allies/allies_ally_leagueofshopkeepers.jpg",
  "Legionary": "images/empires/empires_legionary.jpg",
  "Leprechaun": "images/nocturne/nocturne_leprechaun.jpg",
  "Library": "images/baseset2/baseset2_library.jpg",
  "Lighthouse": "images/seaside/seaside_lighthouse.jpg",
  "Litter": "images/risingsun/risingsun_litter.jpg",
  "Livery": "images/menagerie/menagerie_livery.jpg",
  "Longship": "images/plunder/plunder_longship.jpg",
  "Lookout": "images/seaside/seaside_lookout.jpg",
  "Looting": "images/plunder/plunder_event_looting.jpg",
  "Lost Arts": "images/adventures/adventures_event_lostarts.jpg",
  "Lost City": "images/adventures/adventures_lostcity.jpg",
  "Lucky Coin": "images/nocturne/nocturne_luckycoin.jpg",
  "Lurker": "images/intrigue2add/intrigue2add_lurker.jpg",
  "Madman": "images/darkages/darkages_madman.jpg",
  "Maelstrom": "images/plunder/plunder_event_maelstrom.jpg",
  "Magic Lamp": "images/nocturne/nocturne_magiclamp.jpg",
  "Magnate": "images/prosperity2add/prosperity2add_magnate.jpg",
  "Magpie": "images/adventures/adventures_magpie.jpg",
  "Mapmaker": "images/plunder/plunder_mapmaker.jpg",
  "Marauder": "images/darkages/darkages_marauder.jpg",
  "March": "images/menagerie/menagerie_event_march.jpg",
  "Margrave": "images/hinterlands/hinterlands_margrave.jpg",
  "Market": "images/baseset2/baseset2_market.jpg",
  "Market Square": "images/darkages/darkages_marketsquare.jpg",
  "Market Towns": "images/allies/allies_ally_markettowns.jpg",
  "Maroon": "images/plunder/plunder_maroon.jpg",
  "Marquis": "images/allies/allies_marquis.jpg",
  "Masquerade": "images/intrigue2/intrigue2_masquerade.jpg",
  "Mastermind": "images/menagerie/menagerie_mastermind.jpg",
  "Masterpiece": "images/guilds/guilds_masterpiece.jpg",
  "Menagerie": "images/cornucopia/cornucopia_menagerie.jpg",
  "Mercenary": "images/darkages/darkages_mercenary.jpg",
  "Merchant": "images/baseset2add/baseset2add_merchant.jpg",
  "Merchant Camp": "images/allies/allies_merchantcamp.jpg",
  "Merchant Guild": "images/guilds/guilds_merchantguild.jpg",
  "Merchant Ship": "images/seaside/seaside_merchantship.jpg",
  "Messenger": "images/adventures/adventures_messenger.jpg",
  "Militia": "images/baseset2/baseset2_militia.jpg",
  "Mill": "images/intrigue2add/intrigue2add_mill.jpg",
  "Mine": "images/baseset2/baseset2_mine.jpg",
  "Mining Road": "images/plunder/plunder_miningroad.jpg",
  "Mining Village": "images/intrigue2/intrigue2_miningvillage.jpg",
  "Minion": "images/intrigue2/intrigue2_minion.jpg",
  "Mint": "images/prosperity/prosperity_mint.jpg",
  "Mirror": "images/plunder/plunder_event_mirror.jpg",
  "Miser": "images/adventures/adventures_miser.jpg",
  "Mission": "images/adventures/adventures_event_mission.jpg",
  "Moat": "images/baseset2/baseset2_moat.jpg",
  "Modify": "images/allies/allies_modify.jpg",
  "Monastery": "images/nocturne/nocturne_monastery.jpg",
  "Moneylender": "images/baseset2/baseset2_moneylender.jpg",
  "Monkey": "images/seaside2add/seaside2add_monkey.jpg",
  "Monument": "images/prosperity/prosperity_monument.jpg",
  "Mountain Folk": "images/allies/allies_ally_mountainfolk.jpg",
  "Mountain Pass": "images/empires/empires_landmark_mountainpass.jpg",
  "Mountain Shrine": "images/risingsun/risingsun_mountainshrine.jpg",
  "Mountain Village": "images/renaissance/renaissance_mountainvillage.jpg",
  "Museum": "images/empires/empires_landmark_museum.jpg",
  "Mystic": "images/darkages/darkages_mystic.jpg",
  "Native Village": "images/seaside/seaside_nativevillage.jpg",
  "Nearby": "images/plunder/plunder_trait_nearby.jpg",
  "Necromancer": "images/nocturne/nocturne_necromancer.jpg",
  "Necropolis": "images/darkages/darkages_necropolis.jpg",
  "Night Watchman": "images/nocturne/nocturne_nightwatchman.jpg",
  "Ninja": "images/risingsun/risingsun_ninja.jpg",
  "Nobles": "images/intrigue2/intrigue2_nobles.jpg",
  "Nomads": "images/hinterlands2add/hinterlands2add_nomads.jpg",
  "Oasis": "images/hinterlands/hinterlands_oasis.jpg",
  "Obelisk": "images/empires/empires_landmark_obelisk.jpg",
  "Odysseys": "images/allies/allies_odysseys.jpg",
  "Old Witch": "images/renaissance/renaissance_oldwitch.jpg",
  "Orchard": "images/empires/empires_landmark_orchard.jpg",
  "Order of Astrologers": "images/allies/allies_ally_orderofastrologers.jpg",
  "Order of Masons": "images/allies/allies_ally_orderofmasons.jpg",
  "Outpost": "images/seaside/seaside_outpost.jpg",
  "Overgrown Estate": "images/darkages/darkages_overgrownestate.jpg",
  "Overlord": "images/empires/empires_overlord.jpg",
  "Paddock": "images/menagerie/menagerie_paddock.jpg",
  "Page": "images/adventures/adventures_page.jpg",
  "Pageant": "images/renaissance/renaissance_project_pageant.jpg",
  "Palace": "images/empires/empires_landmark_palace.jpg",
  "Panic": "images/risingsun/risingsun_prophecy_panic.jpg",
  "Pasture": "images/nocturne/nocturne_pasture.jpg",
  "Pathfinding": "images/adventures/adventures_event_pathfinding.jpg",
  "Patient": "images/plunder/plunder_trait_patient.jpg",
  "Patrician / Emporium": "images/empires/empires_patricianemporium.jpg",
  "Patrol": "images/intrigue2add/intrigue2add_patrol.jpg",
  "Patron": "images/renaissance/renaissance_patron.jpg",
  "Pawn": "images/intrigue2/intrigue2_pawn.jpg",
  "Peaceful Cult": "images/allies/allies_ally_peacefulcult.jpg",
  "Peasant": "images/adventures/adventures_peasant.jpg",
  "Peddler": "images/prosperity/prosperity_peddler.jpg",
  "Pendant": "images/plunder/plunder_pendant.jpg",
  "Peril": "images/plunder/plunder_event_peril.jpg",
  "Philosopher's Stone": "images/alchemy/alchemy_philosophersstone.jpg",
  "Piazza": "images/renaissance/renaissance_project_piazza.jpg",
  "Pickaxe": "images/plunder/plunder_pickaxe.jpg",
  "Pilgrim": "images/plunder/plunder_pilgrim.jpg",
  "Pilgrimage": "images/adventures/adventures_event_pilgrimage.jpg",
  "Pillage": "images/darkages/darkages_pillage.jpg",
  "Pious": "images/plunder/plunder_trait_pious.jpg",
  "Pirate": "images/seaside2add/seaside2add_pirate.jpg",
  "Pixie": "images/nocturne/nocturne_pixie.jpg",
  "Plan": "images/adventures/adventures_event_plan.jpg",
  "Plateau Shepherds": "images/allies/allies_ally_plateaushepherds.jpg",
  "Platinum": "images/prosperity/prosperity_platinum.jpg",
  "Plaza": "images/guilds/guilds_plaza.jpg",
  "Poacher": "images/baseset2add/baseset2add_poacher.jpg",
  "Poet": "images/risingsun/risingsun_poet.jpg",
  "Pooka": "images/nocturne/nocturne_pooka.jpg",
  "Poor House": "images/darkages/darkages_poorhouse.jpg",
  "Populate": "images/menagerie/menagerie_event_populate.jpg",
  "Port": "images/adventures/adventures_port.jpg",
  "Possession": "images/alchemy/alchemy_possession.jpg",
  "Potion": "images/alchemy/alchemy_potion.jpg",
  "Pouch": "images/nocturne/nocturne_pouch.jpg",
  "Practice": "images/risingsun/risingsun_event_practice.jpg",
  "Prepare": "images/plunder/plunder_event_prepare.jpg",
  "Priest": "images/renaissance/renaissance_priest.jpg",
  "Prizes": "images/cornucopia/cornucopia_diadem.jpg",
  "Procession": "images/darkages/darkages_procession.jpg",
  "Progress": "images/risingsun/risingsun_prophecy_progress.jpg",
  "Prosper": "images/plunder/plunder_event_prosper.jpg",
  "Province": "images/baseset2/baseset2_province.jpg",
  "Pursue": "images/menagerie/menagerie_event_pursue.jpg",
  "Quarry": "images/prosperity/prosperity_quarry.jpg",
  "Quartermaster": "images/plunder/plunder_quartermaster.jpg",
  "Quest": "images/adventures/adventures_event_quest.jpg",
  "Rabble": "images/prosperity/prosperity_rabble.jpg",
  "Raid": "images/adventures/adventures_event_raid.jpg",
  "Raider": "images/nocturne/nocturne_raider.jpg",
  "Ranger": "images/adventures/adventures_ranger.jpg",
  "Rapid Expansion": "images/risingsun/risingsun_prophecy_rapidexpansion.jpg",
  "Ratcatcher": "images/adventures/adventures_ratcatcher.jpg",
  "Rats": "images/darkages/darkages_rats.jpg",
  "Raze": "images/adventures/adventures_raze.jpg",
  "Reap": "images/menagerie/menagerie_event_reap.jpg",
  "Rebuild": "images/darkages/darkages_rebuild.jpg",
  "Receive Tribute": "images/risingsun/risingsun_event_receivetribute.jpg",
  "Reckless": "images/plunder/plunder_trait_reckless.jpg",
  "Recruiter": "images/renaissance/renaissance_recruiter.jpg",
  "Relic": "images/adventures/adventures_relic.jpg",
  "Remake": "images/cornucopia/cornucopia_remake.jpg",
  "Remodel": "images/baseset2/baseset2_remodel.jpg",
  "Replace": "images/intrigue2add/intrigue2add_replace.jpg",
  "Research": "images/renaissance/renaissance_research.jpg",
  "Rewards": "images/plunder/plunder_wealthyvillage.jpg",
  "Rice": "images/risingsun/risingsun_rice.jpg",
  "Rice Broker": "images/risingsun/risingsun_ricebroker.jpg",
  "Rich": "images/plunder/plunder_trait_rich.jpg",
  "Ride": "images/menagerie/menagerie_event_ride.jpg",
  "Ritual": "images/empires/empires_event_ritual.jpg",
  "River Shrine": "images/risingsun/risingsun_rivershrine.jpg",
  "Riverboat": "images/risingsun/risingsun_riverboat.jpg",
  "Road Network": "images/renaissance/renaissance_project_roadnetwork.jpg",
  "Rogue": "images/darkages/darkages_rogue.jpg",
  "Ronin": "images/risingsun/risingsun_ronin.jpg",
  "Root Cellar": "images/risingsun/risingsun_rootcellar.jpg",
  "Rope": "images/plunder/plunder_rope.jpg",
  "Royal Blacksmith": "images/empires/empires_royalblacksmith.jpg",
  "Royal Cariage": "images/adventures/adventures_royalcarriage.jpg",
  "Royal Carriage": "images/adventures/adventures_royalcarriage.jpg",
  "Royal Galley": "images/allies/allies_royalgalley.jpg",
  "Ruins": "images/darkages/darkages_abandonedmine.jpg",
  "Rush": "images/plunder/plunder_event_rush.jpg",
  "Rustic Village": "images/risingsun/risingsun_rusticvillage.jpg",
  "Sack of Loot": "images/plunder/plunder_sackofloot.jpg",
  "Sacred Grove": "images/nocturne/nocturne_sacredgrove.jpg",
  "Sacrifice": "images/empires/empires_sacrifice.jpg",
  "Sage": "images/darkages/darkages_sage.jpg",
  "Sailor": "images/seaside2add/seaside2add_sailor.jpg",
  "Salt the Earth": "images/empires/empires_event_salttheearth.jpg",
  "Salvager": "images/seaside/seaside_salvager.jpg",
  "Samurai": "images/risingsun/risingsun_samurai.jpg",
  "Sanctuary": "images/menagerie/menagerie_sanctuary.jpg",
  "Save": "images/adventures/adventures_event_save.jpg",
  "Scavenger": "images/darkages/darkages_scavenger.jpg",
  "Scepter": "images/renaissance/renaissance_scepter.jpg",
  "Scheme": "images/hinterlands/hinterlands_scheme.jpg",
  "Scholar": "images/renaissance/renaissance_scholar.jpg",
  "Scouting Party": "images/adventures/adventures_event_scoutingparty.jpg",
  "Scrap": "images/menagerie/menagerie_scrap.jpg",
  "Scrounge": "images/plunder/plunder_event_scrounge.jpg",
  "Scrying Pool": "images/alchemy/alchemy_scryingpool.jpg",
  "Sculptor": "images/renaissance/renaissance_sculptor.jpg",
  "Sea Chart": "images/seaside2add/seaside2add_seachart.jpg",
  "Sea Trade": "images/risingsun/risingsun_event_seatrade.jpg",
  "Sea Witch": "images/seaside2add/seaside2add_seawitch.jpg",
  "Search": "images/plunder/plunder_search.jpg",
  "Seaway": "images/adventures/adventures_event_seaway.jpg",
  "Secluded Shrine": "images/plunder/plunder_secludedshrine.jpg",
  "Secret Cave": "images/nocturne/nocturne_secretcave.jpg",
  "Secret Passage": "images/intrigue2add/intrigue2add_secretpassage.jpg",
  "Seer": "images/renaissance/renaissance_seer.jpg",
  "Seize the Day": "images/menagerie/menagerie_event_seizetheday.jpg",
  "Sentinel": "images/allies/allies_sentinel.jpg",
  "Sentry": "images/baseset2add/baseset2add_sentry.jpg",
  "Settlers / Bustling Village": "images/empires/empires_settlersbustlingvillage.jpg",
  "Sewers": "images/renaissance/renaissance_project_sewers.jpg",
  "Shaman": "images/plunder/plunder_shaman.jpg",
  "Shanty Town": "images/intrigue2/intrigue2_shantytown.jpg",
  "Sheepdog": "images/menagerie/menagerie_sheepdog.jpg",
  "Shelters": "images/darkages/darkages_hovel.jpg",
  "Shepherd": "images/nocturne/nocturne_shepherd.jpg",
  "Shop": "images/guildscornucopia2add/guildscornucopia2add_shop.jpg",
  "Shy": "images/plunder/plunder_trait_shy.jpg",
  "Sickness": "images/risingsun/risingsun_prophecy_sickness.jpg",
  "Silk Merchant": "images/renaissance/renaissance_silkmerchant.jpg",
  "Silos": "images/renaissance/renaissance_project_silos.jpg",
  "Silver": "images/baseset2/baseset2_silver.jpg",
  "Silver Mine": "images/plunder/plunder_silvermine.jpg",
  "Sinister Plot": "images/renaissance/renaissance_project_sinisterplot.jpg",
  "Siren": "images/plunder/plunder_siren.jpg",
  "Skirmisher": "images/allies/allies_skirmisher.jpg",
  "Skulk": "images/nocturne/nocturne_skulk.jpg",
  "Sleigh": "images/menagerie/menagerie_sleigh.jpg",
  "Smithy": "images/baseset2/baseset2_smithy.jpg",
  "Smugglers": "images/seaside/seaside_smugglers.jpg",
  "Snake Witch": "images/risingsun/risingsun_snakewitch.jpg",
  "Snowy Village": "images/menagerie/menagerie_snowyvillage.jpg",
  "Soldier": "images/adventures/adventures_soldier.jpg",
  "Soothsayer": "images/guilds/guilds_soothsayer.jpg",
  "Souk": "images/hinterlands2add/hinterlands2add_souk.jpg",
  "Specialist": "images/allies/allies_specialist.jpg",
  "Spice Merchant": "images/hinterlands/hinterlands_spicemerchant.jpg",
  "Spices": "images/renaissance/renaissance_spices.jpg",
  "Spoils": "images/darkages/darkages_spoils.jpg",
  "Squire": "images/darkages/darkages_squire.jpg",
  "Stables": "images/hinterlands/hinterlands_stables.jpg",
  "Stampede": "images/menagerie/menagerie_event_stampede.jpg",
  "Star Chart": "images/renaissance/renaissance_project_starchart.jpg",
  "Steward": "images/intrigue2/intrigue2_steward.jpg",
  "Stockpile": "images/menagerie/menagerie_stockpile.jpg",
  "Stonemason": "images/guilds/guilds_stonemason.jpg",
  "Storeroom": "images/darkages/darkages_storeroom.jpg",
  "Storyteller": "images/adventures/adventures_storyteller.jpg",
  "Stowaway": "images/plunder/plunder_stowaway.jpg",
  "Supplies": "images/menagerie/menagerie_supplies.jpg",
  "Swamp Hag": "images/adventures/adventures_swamphag.jpg",
  "Swamp Shacks": "images/plunder/plunder_swampshacks.jpg",
  "Swap": "images/allies/allies_swap.jpg",
  "Swashbuckler": "images/renaissance/renaissance_swashbuckler.jpg",
  "Swindler": "images/intrigue2/intrigue2_swindler.jpg",
  "Sycophant": "images/allies/allies_sycophant.jpg",
  "Tactician": "images/seaside/seaside_tactician.jpg",
  "Tanuki": "images/risingsun/risingsun_tanuki.jpg",
  "Taskmaster": "images/plunder/plunder_taskmaster.jpg",
  "Tax": "images/empires/empires_event_tax.jpg",
  "Taxman": "images/guilds/guilds_taxman.jpg",
  "Tea House": "images/risingsun/risingsun_teahouse.jpg",
  "Teacher": "images/adventures/adventures_teacher.jpg",
  "Temple": "images/empires/empires_temple.jpg",
  "The Earth's Gift": "images/nocturne/nocturne_boon_theearthsgift.jpg",
  "The Field's Gift": "images/nocturne/nocturne_boon_thefieldsgift.jpg",
  "The Flame's Gift": "images/nocturne/nocturne_boon_theflamesgift.jpg",
  "The Forest's Gift": "images/nocturne/nocturne_boon_theforestsgift.jpg",
  "The Mountain's Gift": "images/nocturne/nocturne_boon_themountainsgift.jpg",
  "The River's Gift": "images/nocturne/nocturne_boon_theriversgift.jpg",
  "The Sea's Gift": "images/nocturne/nocturne_boon_theseasgift.jpg",
  "The Sky's Gift": "images/nocturne/nocturne_boon_theskysgift.jpg",
  "The Sun's Gift": "images/nocturne/nocturne_boon_thesunsgift.jpg",
  "The Swamp's Gift": "images/nocturne/nocturne_boon_theswampsgift.jpg",
  "The Wind's Gift": "images/nocturne/nocturne_boon_thewindsgift.jpg",
  "Throne Room": "images/baseset2/baseset2_throneroom.jpg",
  "Tiara": "images/prosperity2add/prosperity2add_tiara.jpg",
  "Tide Pools": "images/seaside2add/seaside2add_tidepools.jpg",
  "Tireless": "images/plunder/plunder_trait_tireless.jpg",
  "Toil": "images/menagerie/menagerie_event_toil.jpg",
  "Tomb": "images/empires/empires_landmark_tomb.jpg",
  "Tools": "images/plunder/plunder_tools.jpg",
  "Tormentor": "images/nocturne/nocturne_tormentor.jpg",
  "Torturer": "images/intrigue2/intrigue2_torturer.jpg",
  "Tournament": "images/cornucopia/cornucopia_tournament.jpg",
  "Tower": "images/empires/empires_landmark_tower.jpg",
  "Town": "images/allies/allies_town.jpg",
  "Townsfolk": "images/allies/allies_townsfolk.jpg",
  "Tracker": "images/nocturne/nocturne_tracker.jpg",
  "Trade": "images/adventures/adventures_event_trade.jpg",
  "Trader": "images/hinterlands/hinterlands_trader.jpg",
  "Trading Post": "images/intrigue2/intrigue2_tradingpost.jpg",
  "Tragic Hero": "images/nocturne/nocturne_tragichero.jpg",
  "Trail": "images/hinterlands2add/hinterlands2add_trail.jpg",
  "Training": "images/adventures/adventures_event_training.jpg",
  "Transmogrify": "images/adventures/adventures_transmogrify.jpg",
  "Transmute": "images/alchemy/alchemy_transmute.jpg",
  "Transport": "images/menagerie/menagerie_event_transport.jpg",
  "Trappers' Lodge": "images/allies/allies_ally_trapperslodge.jpg",
  "Travelling Fair": "images/adventures/adventures_event_travellingfair.jpg",
  "Treasure Chest": "images/renaissance/renaissance_treasurechest.jpg",
  "Treasure Hunter": "images/adventures/adventures_treasurehunter.jpg",
  "Treasure Map": "images/seaside/seaside_treasuremap.jpg",
  "Treasure Trove": "images/adventures/adventures_treasuretrove.jpg",
  "Treasurer": "images/renaissance/renaissance_treasurer.jpg",
  "Treasury": "images/seaside/seaside_treasury.jpg",
  "Trickster": "images/plunder/plunder_trickster.jpg",
  "Triumph": "images/empires/empires_event_triumph.jpg",
  "Triumphal Arch": "images/empires/empires_landmark_triumphalarch.jpg",
  "Tunnel": "images/hinterlands/hinterlands_tunnel.jpg",
  "Underling": "images/allies/allies_underling.jpg",
  "University": "images/alchemy/alchemy_university.jpg",
  "Upgrade": "images/intrigue2/intrigue2_upgrade.jpg",
  "Urchin": "images/darkages/darkages_urchin.jpg",
  "Vagrant": "images/darkages/darkages_vagrant.jpg",
  "Vampire": "images/nocturne/nocturne_vampire.jpg",
  "Vassal": "images/baseset2add/baseset2add_vassal.jpg",
  "Vault": "images/prosperity/prosperity_vault.jpg",
  "Villa": "images/empires/empires_villa.jpg",
  "Village": "images/baseset2/baseset2_village.jpg",
  "Village Green": "images/menagerie/menagerie_villagegreen.jpg",
  "Villain": "images/renaissance/renaissance_villain.jpg",
  "Vineyard": "images/alchemy/alchemy_vineyard.jpg",
  "Wall": "images/empires/empires_landmark_wall.jpg",
  "Wandering Minstrel": "images/darkages/darkages_wanderingminstrel.jpg",
  "War Chest": "images/prosperity2add/prosperity2add_warchest.jpg",
  "Warehouse": "images/seaside/seaside_warehouse.jpg",
  "Warrior": "images/adventures/adventures_warrior.jpg",
  "Watchtower": "images/prosperity/prosperity_watchtower.jpg",
  "Way of the Butterfly": "images/menagerie/menagerie_way_wayofthebutterfly.jpg",
  "Way of the Camel": "images/menagerie/menagerie_way_wayofthecamel.jpg",
  "Way of the Chameleon": "images/menagerie/menagerie_way_wayofthechameleon.jpg",
  "Way of the Frog": "images/menagerie/menagerie_way_wayofthefrog.jpg",
  "Way of the Goat": "images/menagerie/menagerie_way_wayofthegoat.jpg",
  "Way of the Horse": "images/menagerie/menagerie_way_wayofthehorse.jpg",
  "Way of the Mole": "images/menagerie/menagerie_way_wayofthemole.jpg",
  "Way of the Monkey": "images/menagerie/menagerie_way_wayofthemonkey.jpg",
  "Way of the Mouse": "images/menagerie/menagerie_way_wayofthemouse.jpg",
  "Way of the Mule": "images/menagerie/menagerie_way_wayofthemule.jpg",
  "Way of the Otter": "images/menagerie/menagerie_way_wayoftheotter.jpg",
  "Way of the Owl": "images/menagerie/menagerie_way_wayoftheowl.jpg",
  "Way of the Ox": "images/menagerie/menagerie_way_wayoftheox.jpg",
  "Way of the Pig": "images/menagerie/menagerie_way_wayofthepig.jpg",
  "Way of the Rat": "images/menagerie/menagerie_way_wayoftherat.jpg",
  "Way of the Seal": "images/menagerie/menagerie_way_wayoftheseal.jpg",
  "Way of the Sheep": "images/menagerie/menagerie_way_wayofthesheep.jpg",
  "Way of the Squirrel": "images/menagerie/menagerie_way_wayofthesquirrel.jpg",
  "Way of the Turtle": "images/menagerie/menagerie_way_wayoftheturtle.jpg",
  "Way of the Worm": "images/menagerie/menagerie_way_wayoftheworm.jpg",
  "Wayfarer": "images/menagerie/menagerie_wayfarer.jpg",
  "Wealthy Village": "images/plunder/plunder_wealthyvillage.jpg",
  "Weaver": "images/hinterlands2add/hinterlands2add_weaver.jpg",
  "Wedding": "images/empires/empires_event_wedding.jpg",
  "Werewolf": "images/nocturne/nocturne_werewolf.jpg",
  "Wharf": "images/seaside/seaside_wharf.jpg",
  "Wheelwright": "images/hinterlands2add/hinterlands2add_wheelwright.jpg",
  "Wild Hunt": "images/empires/empires_wildhunt.jpg",
  "Will-O'-Wisp": "images/nocturne/nocturne_willowisp.jpg",
  "Windfall": "images/empires/empires_event_windfall.jpg",
  "Wine Merchant": "images/adventures/adventures_winemerchant.jpg",
  "Wish": "images/nocturne/nocturne_wish.jpg",
  "Wishing Well": "images/intrigue2/intrigue2_wishingwell.jpg",
  "Witch": "images/baseset2/baseset2_witch.jpg",
  "Witch's Hut": "images/hinterlands2add/hinterlands2add_witchshut.jpg",
  "Wizards": "images/allies/allies_wizards.jpg",
  "Wolf Den": "images/empires/empires_landmark_wolfden.jpg",
  "Woodworker's Guild": "images/allies/allies_ally_woodworkersguild.jpg",
  "Worker's Vilage": "images/prosperity/prosperity_workersvillage.jpg",
  "Worker's Village": "images/prosperity/prosperity_workersvillage.jpg",
  "Workshop": "images/baseset2/baseset2_workshop.jpg",
  "Young Witch": "images/cornucopia/cornucopia_youngwitch.jpg",
  "Zombie Apprentice": "images/nocturne/nocturne_zombieapprentice.jpg",
  "Zombie Mason": "images/nocturne/nocturne_zombiemason.jpg",
  "Zombie Spy": "images/nocturne/nocturne_zombiespy.jpg",
};
